### ISSUE TITLE
World Games No Transparency 

### ISSUE THREAD

**Issue by Breadwinka** [thebezelproject/bezelproject-NES#1]
https://github.com/thebezelproject/bezelproject-NES/blob/238dddf06f6a3783ce9718d3ca0d3c50a08fee90/retroarch/overlay/GameBezels/NES/World%20Games%20(USA).png 

This file has no transparency in the middle so overlay covers game.

**Comment by IceLancerSR** [comment]
[Bezel - World Games (USA).zip](https://github.com/thebezelproject/bezelproject-NES/files/2456202/Bezel.-.World.Games.USA.zip)
here, fixed it for ya

**Comment by thebezelproject** [comment]
Sorry for the delay. The png has been updated.
