### ISSUE TITLE
Overlays contain transparent / translucent pixels outside the desired area

### ISSUE THREAD

**Issue by toniosj** [thebezelproject/bezelproject-NES#3]
Some overlays contain transparent / translucent pixels outside the desired area.

Here the list:

Advanced Dungeons & Dragons - Hillsfar (USA).png
Adventures of Dr. Franken, The (USA) (Proto).png
Adventures of Gilligan's Island, The (USA).png
Caesars Palace (USA).png
California Games (USA).png
Caltron - 6 in 1 (USA) (Unl).png
Captain Comic - The Adventure (USA) (Unl).png
Chris Evert & Ivan Lendl in Top Players' Tennis (USA).png
Cybernoid - The Fighting Machine (USA).png
Faxanadu (USA) (Rev A).png
Felix the Cat (USA).png
Fisher-Price - I Can Remember (USA).png
Metal Gear (USA).png
Metal Mech - Man & Machine (USA).png
Monster Party (USA).png
MotorCity Patrol (USA).png
Nintendo World Cup (USA).png
P.O.W. - Prisoners of War (USA).png
Pac-Mania (USA) (Unl).png
Palamedes (USA).png
Paperboy 2 (USA).png
Parasol Stars - Rainbow Islands II (Europe).png
Puzznic (USA).png
QIX (USA).png
Top Gun (USA) (Rev A).png
Total Funpak (Australia) (Unl).png
Touch Down Fever (USA).png
Treasure Master (USA).png
Trolls on Treasure Island (USA) (Unl).png
Whomp 'Em (USA).png
Wrath of the Black Manta (USA) (Rev A).png
WWF Wrestlemania Steel Cage Challenge (USA).png
Xevious - The Avenger (USA).png
Xexyz (USA).png
Yo! Noid (USA).png
Zanac (USA).png

Here you can see the specific areas that have pixels outside the desired area.

https://drive.google.com/file/d/1o_9rQYC6b_2o_2Uzh-MBhuT9filglSll/view?usp=sharing

**Comment by thebezelproject** [comment]
Many thanks! These have been updated.
