### ISSUE TITLE
Transparent pixles

### ISSUE THREAD

**Issue by toniosj** [thebezelproject/bezelproject-NES#7]
1942 (Japan, USA).png
Magic Darts (USA).png
World Games (USA).png  (It doesn't have trasnparent zone)
Sesame Street 123 (USA).png
Popeye (World) (Rev A).png

![World Games (USA)_bezel-16-9(us) - 1_yellow](https://user-images.githubusercontent.com/20826760/101359064-097a5d80-389c-11eb-9fc2-170f920376e3.png)
![Popeye (World) (Rev A)_bezel-16-9(wor) - 1_yellow](https://user-images.githubusercontent.com/20826760/101359348-6a099a80-389c-11eb-9d36-79d5bdc1c957.png)
![Sesame Street 123 (USA)_bezel-16-9(us) - 1_yellow](https://user-images.githubusercontent.com/20826760/101359177-32025780-389c-11eb-8552-4fb49a6596b0.png)
![Magic Darts (USA)_bezel-16-9(us) - 1_yellow](https://user-images.githubusercontent.com/20826760/101358897-cddf9380-389b-11eb-839e-4d39b75e71d1.png)
![1942 (Japan, USA)_bezel-16-9(wor) - 1_yellow](https://user-images.githubusercontent.com/20826760/101358905-d20bb100-389b-11eb-9bbc-1aab0c03a910.png)

**Comment by thebezelproject** [comment]
Updated files.
